name: build-native
on:
  workflow_dispatch:
    inputs: {}
#  schedule:
#    - cron: '0 0 * * *'
env:
  BUILD_TYPE: Release

jobs:
  build-android:
    name: android
    runs-on: ubuntu-20.04
    env:
      NDK_VER: 23.1.7779620
      PLATFORM_VER: android-34
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: |
            11
            17

      - name: Install Android SDK Manager
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Install Android SDK
        run: |
          sdkmanager --install "platform-tools" "platforms;$PLATFORM_VER"
          sdkmanager --install "ndk;$NDK_VER" --channel=3

      - name: Build (Android)
        run: |
          export PATH=$ANDROID_HOME/ndk/$NDK_VER:$PATH
          export OUTPUT=$PWD/native/android
          rm -rf $OUTPUT && mkdir -p $OUTPUT

          # Build SDL2
          sed -i 's/abi=.*/abi="armeabi-v7a arm64-v8a x86 x86_64"/g' ./External/SDL/build-scripts/androidbuildlibs.sh
          ./External/SDL/build-scripts/androidbuildlibs.sh NDK_LIBS_OUT="$OUTPUT"

      - name: Build SDL2 Android Java
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          export PATH=$JAVA_HOME_11_X64/bin:$PATH
          export OUTPUT=$PWD/SDL2-CS.Android/Jars/
          rm -rf $OUTPUT && mkdir -p $OUTPUT

          # Build SDL2 Android Java part
          cd ./External/SDL/android-project/app/src/main/java
          javac -cp $ANDROID_HOME/platforms/$PLATFORM_VER/android.jar -encoding utf8 org/libsdl/app/*.java
          jar cvf $OUTPUT/SDL2AndroidBridge.jar org/libsdl/app/*.class

      - name: Compress native directory
        run: tar -cf native-android.tar native/android

      - name: Upload native artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-android
          path: native-android.tar
          if-no-files-found: error

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-jar
          path: SDL2-CS.Android/Jars/SDL2AndroidBridge.jar
          if-no-files-found: error

  make-pr:
    name: Submit pull request
    runs-on: ubuntu-latest
    needs: [ build, build-ios, build-android ]
    steps:
      - uses: actions/checkout@v4

      - name: Download native artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: native-*
          merge-multiple: true

      - name: Decompress native artifacts
        run: |
          for file in native-*.tar
          do
            tar -xf "$file"
          done
          rm native-*.tar

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: android-jar
          path: SDL2-CS.Android/Jars/

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update native binaries
          title: Update native binaries
          body: This PR has been auto-generated to update the native SDL binaries
          branch: update-native-binaries
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'